### PR TITLE
Remove duplicate tags

### PR DESCRIPTION
**Pull request by paurosello**
## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by fiunchinho** [comment]
[We have this function here](https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/iam/oidc.go#L334-L345) that does a similar thing. [It's used here](https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/iam/oidc.go#L85). Does it make sense to make it public and reuse?

**Comment by paurosello** [comment]
> [We have this function here](https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/iam/oidc.go#L334-L345) that does a similar thing. [It's used here](https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/iam/oidc.go#L85). Does it make sense to make it public and reuse?

yeah, the problem is the types, each AWS object has it's own type and not sure how to make it generic

**Comment by paurosello** [comment]
I refactored the function using reflect (as each AWS package uses a different struct :() let me know if this feels too hacky

**Review by fiunchinho — CHANGES_REQUESTED** [review]
Drop a note in the CHANGELOG and I think this is fine.

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
